apiVersion: v1
kind: Service
metadata:
  name: secure-pay-kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
    - port: 2181
      targetPort: 2181
      name: zookeeper
    - port: 3030
      targetPort: 3030
      name: ui
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-pay-kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: lensesio/fast-data-dev:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ADV_HOST
              value: "secure-pay-kafka"
            - name: RUN_TESTS
              value: "0"
            - name: SAMPLEDATA
              value: "0"
          ports:
            - containerPort: 9092
            - containerPort: 2181
            - containerPort: 3030
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "750Mi"
              cpu: "500m"
