apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: default
data:
  # SPIFFE Endpoint Socket
  SPIFFE_ENDPOINT_SOCKET: "unix:///run/spire/sockets/agent.sock"
  # Trust Domain
  TRUST_DOMAIN: "securepay.dev"
  # Application Port
  PORT: "8080"
  # Service Connection Details (gRPC)
  PAYMENT_SERVICE_ADDR: "payment-service:8081"
  ACCOUNT_SERVICE_ADDR: "account-service:8082"
