apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: default
data:
  # SPIFFE Endpoint Socket
  SPIFFE_ENDPOINT_SOCKET: "unix:///tmp/spire-agent/public/api.sock"
  # Trust Domain
  TRUST_DOMAIN: "securepay.dev"
  # Application Port
  PORT: ":8082"
  # Kafka Configuration
  KAFKA_BROKERS: "secure-pay-kafka.default.svc.cluster.local:9092"
  KAFKA_TOPIC: "payment.initiated"
  # Database Configuration
  DATABASE_URL: "postgres://securepay:password@my-postgres-postgresql:5432/securepay?sslmode=disable"
